modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPL-3.0"

[[mods]]
modId = "dingdongji"
version = "${file.jarVersion}"
displayName = "AnvilCraft-DingDongJi"
credits = "WPS灵犀"
authors = "_054k"
description = '''AnvilCraft-DingDongJi - 铁砧工艺扩展模组
包含叽砧、叽装备、黑洞剑、白洞剑、创造模板及三套定制盔甲（皇家钢、余烬金属、超限合金）。
Requires AnvilCraft as dependency.
'''

[[dependencies.dingdongji]]
    modId = "anvilcraft"
    mandatory = true
    versionRange = "[1.5,1.7)"
    ordering = "NONE"
    side = "BOTH"

[[mixins]]
config = "dingdongji.mixins.json"

